=== AR2000AR/PTS2/data/niveau.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="niveau">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element name="description">
    				<xs:simpleType>
    					<xs:restriction base="xs:string">
    						<xs:pattern value="((0|1)(0|1|2|3){2}){4}"></xs:pattern>
    					</xs:restriction>
    				</xs:simpleType>
    			</xs:element>
    		</xs:sequence>
    		<xs:attribute name="nbNiveau" use="required">
    			<xs:simpleType>
    				<xs:restriction base="xs:int">
    					<xs:maxInclusive value="5"></xs:maxInclusive>
    					<xs:minInclusive value="0"></xs:minInclusive>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:attribute>
    		<xs:attribute name="nbContext" use="required">
    			<xs:simpleType>
    				<xs:restriction base="xs:int">
    					<xs:maxInclusive value="1"></xs:maxInclusive>
    					<xs:minInclusive value="0"></xs:minInclusive>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:attribute>
    		<xs:attribute name="nbDifficulte" use="required">
    			<xs:simpleType>
    				<xs:restriction base="xs:int">
    					<xs:minInclusive value="0"></xs:minInclusive>
    					<xs:maxInclusive value="3"></xs:maxInclusive>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:attribute>
    	</xs:complexType>
    </xs:element>

    <xs:element name="root">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="niveau" minOccurs="48" maxOccurs="48"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
</xs:schema>

=== AR2000AR/PTS2/data/niveau.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="niveau.xsd">
  <niveau nbContext="0" nbDifficulte="0" nbNiveau="0">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="0" nbDifficulte="0" nbNiveau="1">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="0" nbDifficulte="0" nbNiveau="2">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="0" nbDifficulte="0" nbNiveau="3">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="0" nbDifficulte="0" nbNiveau="4">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="0" nbDifficulte="0" nbNiveau="5">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="0" nbDifficulte="1" nbNiveau="0">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="0" nbDifficulte="1" nbNiveau="1">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="0" nbDifficulte="1" nbNiveau="2">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="0" nbDifficulte="1" nbNiveau="3">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="0" nbDifficulte="1" nbNiveau="4">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="0" nbDifficulte="1" nbNiveau="5">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="0" nbDifficulte="2" nbNiveau="0">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="0" nbDifficulte="2" nbNiveau="1">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="0" nbDifficulte="2" nbNiveau="2">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="0" nbDifficulte="2" nbNiveau="3">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="0" nbDifficulte="2" nbNiveau="4">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="0" nbDifficulte="2" nbNiveau="5">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="0" nbDifficulte="3" nbNiveau="0">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="0" nbDifficulte="3" nbNiveau="1">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="0" nbDifficulte="3" nbNiveau="2">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="0" nbDifficulte="3" nbNiveau="3">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="0" nbDifficulte="3" nbNiveau="4">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="0" nbDifficulte="3" nbNiveau="5">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="1" nbDifficulte="0" nbNiveau="0">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="1" nbDifficulte="0" nbNiveau="1">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="1" nbDifficulte="0" nbNiveau="2">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="1" nbDifficulte="0" nbNiveau="3">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="1" nbDifficulte="0" nbNiveau="4">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="1" nbDifficulte="0" nbNiveau="5">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="1" nbDifficulte="1" nbNiveau="0">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="1" nbDifficulte="1" nbNiveau="1">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="1" nbDifficulte="1" nbNiveau="2">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="1" nbDifficulte="1" nbNiveau="3">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="1" nbDifficulte="1" nbNiveau="4">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="1" nbDifficulte="1" nbNiveau="5">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="1" nbDifficulte="2" nbNiveau="0">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="1" nbDifficulte="2" nbNiveau="1">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="1" nbDifficulte="2" nbNiveau="2">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="1" nbDifficulte="2" nbNiveau="3">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="1" nbDifficulte="2" nbNiveau="4">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="1" nbDifficulte="2" nbNiveau="5">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="1" nbDifficulte="3" nbNiveau="0">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="1" nbDifficulte="3" nbNiveau="1">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="1" nbDifficulte="3" nbNiveau="2">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="1" nbDifficulte="3" nbNiveau="3">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="1" nbDifficulte="3" nbNiveau="4">
    <description>000000000000</description>
  </niveau>
  <niveau nbContext="1" nbDifficulte="3" nbNiveau="5">
    <description>000000000000</description>
  </niveau>
</root>
